// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApiAuthMeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/show_user_info_controller.ts').default['handle'], false>
}
type ApiAuthRedirectGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/discord_redirect_controller.ts').default['handle'], false>
}
type ApiAuthCallbackGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/discord_callback_controller.ts').default['handle'], false>
}
type ApiAuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/logout_controller.ts').default['handle'], false>
}
type ApiDiscordIdSchedulesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/discord/controllers/list_user_schedule_controller.ts').default['handle'], false>
}
type ApiMedicationsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/medication/controllers/list_medication_controller.ts').default['handle'], false>
}
type ApiMedicationsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/medication/controllers/create_medication_controller.ts').default['handle'], false>
}
type ApiMedicationsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/medication/controllers/show_medication_controller.ts').default['handle'], false>
}
type ApiMedicationsIdPut = {
  request: unknown
  response: MakeTuyauResponse<import('../app/medication/controllers/update_medication_controller.ts').default['handle'], false>
}
type ApiMedicationsIdArchivePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/medication/controllers/toggle_archive_medication_controller.ts').default['handle'], false>
}
type ApiMedicationsIdSchedulesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/schedule/controllers/list_schedule_controller.ts').default['handle'], false>
}
type ApiMedicationsIdSchedulesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/schedule/controllers/add_schedule_controller.ts').default['handle'], false>
}
type ApiMedicationsIdSchedulesIdArchivePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/schedule/controllers/toggle_active_schedule_controller.ts').default['handle'], false>
}
type ApiMedicationsIdSchedulesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/schedule/controllers/delete_schedule_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'api': {
    'auth': {
      'me': {
        '$url': {
        };
        '$get': ApiAuthMeGetHead;
        '$head': ApiAuthMeGetHead;
      };
      'redirect': {
        '$url': {
        };
        '$get': ApiAuthRedirectGetHead;
        '$head': ApiAuthRedirectGetHead;
      };
      'callback': {
        '$url': {
        };
        '$get': ApiAuthCallbackGetHead;
        '$head': ApiAuthCallbackGetHead;
      };
      'logout': {
        '$url': {
        };
        '$post': ApiAuthLogoutPost;
      };
    };
    'discord': {
      ':discordId': {
        'schedules': {
          '$url': {
          };
          '$get': ApiDiscordIdSchedulesGetHead;
          '$head': ApiDiscordIdSchedulesGetHead;
        };
      };
    };
    'medications': {
      '$url': {
      };
      '$get': ApiMedicationsGetHead;
      '$head': ApiMedicationsGetHead;
      '$post': ApiMedicationsPost;
      ':medicationId': {
        '$url': {
        };
        '$get': ApiMedicationsIdGetHead;
        '$head': ApiMedicationsIdGetHead;
        '$put': ApiMedicationsIdPut;
        'archive': {
          '$url': {
          };
          '$post': ApiMedicationsIdArchivePost;
        };
        'schedules': {
          '$url': {
          };
          '$get': ApiMedicationsIdSchedulesGetHead;
          '$head': ApiMedicationsIdSchedulesGetHead;
          '$post': ApiMedicationsIdSchedulesPost;
          ':scheduleId': {
            'archive': {
              '$url': {
              };
              '$post': ApiMedicationsIdSchedulesIdArchivePost;
            };
            '$url': {
            };
            '$delete': ApiMedicationsIdSchedulesIdDelete;
          };
        };
      };
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
