// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApiAuthMeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/show_user_info_controller.ts').default['handle'], false>
}
type ApiAuthRedirectGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/discord_redirect_controller.ts').default['handle'], false>
}
type ApiAuthCallbackGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/discord_callback_controller.ts').default['handle'], false>
}
type ApiAuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/logout_controller.ts').default['handle'], false>
}
type ApiMedicationsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/medication/controllers/create_medication_controller.ts').default['handle'], false>
}
type ApiMedicationsIdSchedulesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/schedule/controllers/add_schedule_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'api': {
    'auth': {
      'me': {
        '$url': {
        };
        '$get': ApiAuthMeGetHead;
        '$head': ApiAuthMeGetHead;
      };
      'redirect': {
        '$url': {
        };
        '$get': ApiAuthRedirectGetHead;
        '$head': ApiAuthRedirectGetHead;
      };
      'callback': {
        '$url': {
        };
        '$get': ApiAuthCallbackGetHead;
        '$head': ApiAuthCallbackGetHead;
      };
      'logout': {
        '$url': {
        };
        '$post': ApiAuthLogoutPost;
      };
    };
    'medications': {
      '$url': {
      };
      '$post': ApiMedicationsPost;
      ':medicationId': {
        'schedules': {
          '$url': {
          };
          '$post': ApiMedicationsIdSchedulesPost;
        };
      };
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
